In [ ]:
import pandas as pd
from dataAccess import nj_pickle_to_df

allYears = list(range(2020, 2025))
allFires = {}
allAddresses = {}
for y in allYears:
    allFires[y] = nj_pickle_to_df(y, 'fireincident')
    allAddresses[y] = nj_pickle_to_df(y, 'incidentaddress')

fiCols = allFires[2024].columns
iaCols = allAddresses[2024].columns
inBoth = list(set(fiCols).intersection(set(iaCols)))
#print(f"iaCols: {iaCols}")
print(f"Columns in both: {inBoth}")

mergedDfs = {}
for y in allYears:
    mergedDfs[y] = pd.merge(allFires[y], allAddresses[y], on=inBoth)

#print(f"All columns: {fiDfs[2020].columns}")
#print(f"Unique for CAUSE_IGN: {fiDfs[2020]['CAUSE_IGN'].value_counts()}")
#print(f"Unique for FIRST_IGN: {fiDfs[2020]['FIRST_IGN'].value_counts()}")
#print(f"Number of empty values for incident keys: {fiDfs[2020]['INCIDENT_KEY'].isna().sum()}")
#print(f"Number of empty values for cause of ignition: {fiDfs[2020]['CAUSE_IGN'].isna().sum()}")

05-16-2026 17:01:45 - dataAccess: Reading compressed_data\nj_2020_fireincident.pkl.gz
05-16-2026 17:01:45 - dataAccess: Reading compressed_data\nj_2020_incidentaddress.pkl.gz
05-16-2026 17:01:46 - dataAccess: Reading compressed_data\nj_2021_fireincident.pkl.gz
05-16-2026 17:01:46 - dataAccess: Reading compressed_data\nj_2021_incidentaddress.pkl.gz
05-16-2026 17:01:46 - dataAccess: Reading compressed_data\nj_2022_fireincident.pkl.gz
05-16-2026 17:01:46 - dataAccess: Reading compressed_data\nj_2022_incidentaddress.pkl.gz
05-16-2026 17:01:46 - dataAccess: Reading compressed_data\nj_2023_fireincident.pkl.gz
05-16-2026 17:01:46 - dataAccess: Reading compressed_data\nj_2023_incidentaddress.pkl.gz
05-16-2026 17:01:47 - dataAccess: Reading compressed_data\nj_2024_fireincident.pkl.gz
05-16-2026 17:01:47 - dataAccess: Reading compressed_data\nj_2024_incidentaddress.pkl.gz
Columns in both: ['EXP_NO', 'INCIDENT_KEY', 'FDID', 'STATE', 'INC_NO', 'INC_DATE']

In [14]:
merged2024df = mergedDfs[2024]
merged2024df.head(10)

,INCIDENT_KEY,STATE,FDID,INC_DATE,INC_NO,EXP_NO,VERSION,NUM_UNIT,NOT_RES,BLDG_INVOL,...,STREET_PRE,STREETNAME,STREETTYPE,STREETSUF,APT_NO,CITY,STATE_ID,ZIP5,ZIP4,X_STREET
0,NJ_01011_02112024_35_0,NJ,01011,02112024,35,0,5.0,,Y,,...,,minnetonka,AVE,,,Absecon,NJ,08201,,
1,NJ_01011_04052024_75_0,NJ,01011,04052024,75,0,5.0,,N,,...,,Absecon,BLVD,,,Absecon,NJ,08201,,
2,NJ_01011_04282024_97_0,NJ,01011,04282024,97,0,5.0,1,N,1,...,,Hobart,AVE,,,Absecon,NJ,08201,,
3,NJ_01011_04282024_98_0,NJ,01011,04282024,98,0,5.0,,Y,,...,,rt 30,,,,Absecon,NJ,08201,,Delilah rd
4,NJ_01011_05222024_115_0,NJ,01011,05222024,115,0,5.0,,Y,,...,,White Horse,PIKE,,,Absecon,NJ,08201,,
5,NJ_01011_05302024_123_0,NJ,01011,05302024,123,0,5.0,,N,,...,,White Horse,PIKE,,,Absecon,NJ,08201,,
6,NJ_01011_06162024_138_0,NJ,01011,06162024,138,0,5.0,,N,,...,,Absecon Blvd,BLVD,,,Absecon,NJ,08201,,
7,NJ_01011_06242024_144_0,NJ,01011,06242024,144,0,5.0,,N,,...,,White Horse,PIKE,,,Absecon,NJ,08201,,
8,NJ_01011_08062024_176_0,NJ,01011,08062024,176,0,5.0,,N,,...,,White Horse Pike,PIKE,,,Absecon,NJ,08201,,
9,NJ_01011_08062024_177_0,NJ,01011,08062024,177,0,5.0,,N,,...,,White Horse Pike,PIKE,,,Absecon,NJ,08201,,

In [18]:
ww2024df = merged2024df[merged2024df['ZIP5'] == '08550']
ww2024df.head(10)

,INCIDENT_KEY,STATE,FDID,INC_DATE,INC_NO,EXP_NO,VERSION,NUM_UNIT,NOT_RES,BLDG_INVOL,...,STREET_PRE,STREETNAME,STREETTYPE,STREETSUF,APT_NO,CITY,STATE_ID,ZIP5,ZIP4,X_STREET
6119,NJ_11001_06302024_0003495_0,NJ,11001,06302024,0003495,0,5.0,1,N,,...,,Cranbury,RD,,,West Windsor,NJ,08550,,Cranbury RdJoa
6141,NJ_11001_08192024_0004476_0,NJ,11001,08192024,0004476,0,5.0,1,N,,...,,Auburn,PL,,,West Windsor,NJ,08550,,Oxford CtColum
6474,NJ_11043_01172024_29_0,NJ,11043,01172024,29,0,5.0,1,N,0,...,,Conover,RD,,,West Windsor,NJ,08550,,
6475,NJ_11043_02222024_84_0,NJ,11043,02222024,84,0,5.0,1,N,1,...,,Old Trenton,RD,,,West Windsor,NJ,08550,,
6476,NJ_11043_05282024_302_0,NJ,11043,05282024,302,0,5.0,0,N,1,...,,Lancaster,CT,,,West Windsor,NJ,08550,,
6477,NJ_11043_06232024_363_0,NJ,11043,06232024,363,0,5.0,0,Y,0,...,,Southfield,RD,,,West Windsor,NJ,08550,,
6482,NJ_11044_03262024_153_0,NJ,11044,03262024,153,0,5.0,0,Y,0,...,,Clarksville,RD,,,West Windsor,NJ,08550,,
6484,NJ_11044_04262024_208_0,NJ,11044,04262024,208,0,5.0,0,Y,0,...,,Clarksville,RD,,,West Windsor,NJ,08550,,
6489,NJ_11044_05312024_281_0,NJ,11044,05312024,281,0,5.0,0,Y,0,...,,Vaughn,DR,,,Princeton Junction,NJ,08550,,
6493,NJ_11044_06172024_312_0,NJ,11044,06172024,312,0,5.0,0,Y,0,...,,Cranbury,RD,,,West Windsor,NJ,08550,,

In [21]:
ww2024df['STREETNAME'].unique()

array(['Cranbury', 'Auburn', 'Conover', 'Old Trenton', 'Lancaster',
       'Southfield', 'Clarksville', 'Vaughn', 'Princeton Hightstown',
       'Hereford', 'Alexander', 'Winterberry', 'Douglas',
       '2031 Old Trenton Road', 'US 1', 'Raritan', 'Washington'],
      dtype=object)

In [22]:
ww2024df.columns

Index(['INCIDENT_KEY', 'STATE', 'FDID', 'INC_DATE', 'INC_NO', 'EXP_NO',
       'VERSION', 'NUM_UNIT', 'NOT_RES', 'BLDG_INVOL', 'ACRES_BURN',
       'LESS_1ACRE', 'ON_SITE_M1', 'MAT_STOR1', 'ON_SITE_M2', 'MAT_STOR2',
       'ON_SITE_M3', 'MAT_STOR3', 'AREA_ORIG', 'HEAT_SOURC', 'FIRST_IGN',
       'CONF_ORIG', 'TYPE_MAT', 'CAUSE_IGN', 'FACT_IGN_1', 'FACT_IGN_2',
       'HUM_FAC_1', 'HUM_FAC_2', 'HUM_FAC_3', 'HUM_FAC_4', 'HUM_FAC_5',
       'HUM_FAC_6', 'HUM_FAC_7', 'HUM_FAC_8', 'AGE', 'SEX', 'EQUIP_INV',
       'SUP_FAC_1', 'SUP_FAC_2', 'SUP_FAC_3', 'MOB_INVOL', 'MOB_TYPE',
       'MOB_MAKE', 'MOB_MODEL', 'MOB_YEAR', 'MOB_LIC_PL', 'MOB_STATE',
       'MOB_VIN_NO', 'EQ_BRAND', 'EQ_MODEL', 'EQ_SER_NO', 'EQ_YEAR',
       'EQ_POWER', 'EQ_PORT', 'FIRE_SPRD', 'STRUC_TYPE', 'STRUC_STAT',
       'BLDG_ABOVE', 'BLDG_BELOW', 'BLDG_LGTH', 'BLDG_WIDTH', 'TOT_SQ_FT',
       'FIRE_ORIG', 'ST_DAM_MIN', 'ST_DAM_SIG', 'ST_DAM_HVY', 'ST_DAM_XTR',
       'FLAME_SPRD', 'ITEM_SPRD', 'MAT_SPRD', 'DETECTOR', 'DET_TYPE',
       'DET_POWER', 'DET_OPERAT', 'DET_EFFECT', 'DET_FAIL', 'AES_PRES',
       'AES_TYPE', 'AES_OPER', 'NO_SPR_OP', 'AES_FAIL', 'LOC_TYPE', 'NUM_MILE',
       'STREET_PRE', 'STREETNAME', 'STREETTYPE', 'STREETSUF', 'APT_NO', 'CITY',
       'STATE_ID', 'ZIP5', 'ZIP4', 'X_STREET'],
      dtype='object')

In [ ]:
ww_danger_df = ww2024df['']